// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfho43FwYRPcp5MlCQ8Qjn6PDPl1NjxYU',
    appId: '1:145042052463:web:926469ef86a07a7a5f049a',
    messagingSenderId: '145042052463',
    projectId: 'restaurantapp-1942f',
    authDomain: 'restaurantapp-1942f.firebaseapp.com',
    storageBucket: 'restaurantapp-1942f.firebasestorage.app',
    measurementId: 'G-3CW8FJ51Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHL1f_VTPBI6MYdBjNpmQWV2gHHucPi08',
    appId: '1:145042052463:android:6ee0f74f349b8f085f049a',
    messagingSenderId: '145042052463',
    projectId: 'restaurantapp-1942f',
    storageBucket: 'restaurantapp-1942f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9tUSTBQleZU-nZUfIRIlFjsRbeuYBjyM',
    appId: '1:145042052463:ios:ee98faccb2f4614c5f049a',
    messagingSenderId: '145042052463',
    projectId: 'restaurantapp-1942f',
    storageBucket: 'restaurantapp-1942f.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9tUSTBQleZU-nZUfIRIlFjsRbeuYBjyM',
    appId: '1:145042052463:ios:ee98faccb2f4614c5f049a',
    messagingSenderId: '145042052463',
    projectId: 'restaurantapp-1942f',
    storageBucket: 'restaurantapp-1942f.firebasestorage.app',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfho43FwYRPcp5MlCQ8Qjn6PDPl1NjxYU',
    appId: '1:145042052463:web:0bfbab33796b72555f049a',
    messagingSenderId: '145042052463',
    projectId: 'restaurantapp-1942f',
    authDomain: 'restaurantapp-1942f.firebaseapp.com',
    storageBucket: 'restaurantapp-1942f.firebasestorage.app',
    measurementId: 'G-HBRH4FZW1X',
  );
}
